
  name: eca-final backend-platform GCP Deployment

  on: push

  jobs:
    deploy:
      runs-on: ubuntu-latest

      permissions:
        contents: read
        id-token: write

      steps:
        - name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v3
          with:
            workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
            service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
            project_id: ${{ secrets.GCP_PROJECT_ID }}

        - name: Set up Google Cloud SDK
          uses: google-github-actions/setup-gcloud@v3

        - name: Start vm-platform-seed
          run: |
            gcloud compute instances start vm-platform-seed \
              --zone=asia-southeast1-b

        - name: Connect to vm-platform-seed, pull latest code and build
          run: |
            gcloud compute ssh tharusanduni33@vm-platform-seed \
              --zone=asia-southeast1-b \
              --command="cd ~/backend-platform && git pull --recurse-submodules && source ~/.bashrc && mvn clean package -DskipTests"

        - name: Stop vm-platform-seed instance
          run: |
            gcloud compute instances stop vm-platform-seed \
              --zone=asia-southeast1-b

        - name: Delete the image
          run: |
            gcloud compute images delete vm-platform-seed-boot-image-v2 

        - name: Create a new image with the previous image name
          run: |
            gcloud compute images create vm-platform-seed-boot-image-v2 \
             --source-disk=vm-platform-seed \
              --source-disk-zone=asia-southeast1-b \
            --storage-location=asia-southeast1
